/**
 * Normalization Types - Canonical Source of Truth
 *
 * Single source of truth for ALL normalization-related types.
 * These types are used throughout the normalization system and must match DB schema.
 */

// ============================================================================
// MARKET CATEGORY
// ============================================================================

/**
 * Market categories for UI organization (following Superbet pattern)
 */
export const MarketCategory = {
  /** Match result markets - 1X2, Double Chance, Draw No Bet */
  WYNIK_MECZU: "WYNIK_MECZU",

  /** Goals markets - BTTS, Over/Under, Odd/Even, Win to Nil, Clean Sheet */
  GOLE: "GOLE",

  /** Handicap markets - Asian Handicap, European Handicap */
  HANDICAP: "HANDICAP",

  /** Half markets - 1st half, 2nd half results and goals */
  POLOWY: "POLOWY",

  /** Correct Score markets */
  DOKLADNY_WYNIK: "DOKLADNY_WYNIK",

  /** Player props - goalscorers, cards, assists */
  ZAWODNICY: "ZAWODNICY",

  /** Statistics - corners, team cards, fouls */
  STATYSTYKI: "STATYSTYKI",

  /** Combination markets - Result+BTTS, Result+O/U, HT/FT */
  KOMBINACJE: "KOMBINACJE",

  /** Other markets - truly unknown/special markets */
  INNE: "INNE",
} as const;
export type MarketCategory = (typeof MarketCategory)[keyof typeof MarketCategory];

// ============================================================================
// VIEW TYPE
// ============================================================================

/**
 * View type determines how market is rendered in UI (string form shared with DB enums)
 */
export const ViewType = {
  BINARY_BUTTONS: "BINARY_BUTTONS",     // YES/NO, OVER/UNDER - 2 simple buttons
  TRIPLE_BUTTONS: "TRIPLE_BUTTONS",     // 1X2 - 3 buttons (Home, Draw, Away)
  PARAMETER_SLIDER: "PARAMETER_SLIDER",   // Over/Under with parameter selection (2.5, 3.5, etc.)
  HANDICAP_SELECTOR: "HANDICAP_SELECTOR",  // Handicap markets with +/- values
  SCORE_GRID: "SCORE_GRID",             // Correct score - grid of scores
  PLAYER_DROPDOWN: "PLAYER_DROPDOWN",    // Goalscorer - dropdown + single odds per player
  PLAYER_STAT_LINES: "PLAYER_STAT_LINES", // Player stat markets - player selector + line thresholds (1+, 2+, etc.)
  STAT_RANGE: "STAT_RANGE",              // Corners, Cards - range selector
  COMBINATION: "COMBINATION",             // Combined markets (Result + BTTS)
  PARAMETERIZED_COMBINATION: "PARAMETERIZED_COMBINATION", // Player combination markets with parameter support (e.g., 2/3 Players Combined Goals)
  HALFTIME_FULLTIME: "HALFTIME_FULLTIME", // 9 outcomes HT/FT grid
  SINGLE_SELECTION: "SINGLE_SELECTION",   // Single selection market (e.g., "Hat-trick", "Red card", "Free kick goal")
} as const;
export type ViewType = (typeof ViewType)[keyof typeof ViewType];

// ============================================================================
// PARAMETER TYPE
// ============================================================================

/**
 * Parameter types for markets with line values
 */
export const ParameterType = {
  DECIMAL: "decimal",
  INTEGER: "integer",
  HANDICAP: "handicap",
  SCORE: "score",
  PLAYER: "player",
  TEAM: "team",
} as const;
export type ParameterType = (typeof ParameterType)[keyof typeof ParameterType];

// ============================================================================
// NORMALIZED MARKET TYPE
// ============================================================================

/**
 * Normalized market types (canonical codes used throughout system)
 */
export const NormalizedMarketType = {
  // Main markets
  MATCH_WINNER: "MATCH_WINNER",
  DOUBLE_CHANCE: "DOUBLE_CHANCE",
  DRAW_NO_BET: "DRAW_NO_BET",
  // Goals markets
  TOTAL_GOALS: "TOTAL_GOALS",
  TOTAL_GOALS_ASIAN: "TOTAL_GOALS_ASIAN", // Integer lines with push/refund possibility
  EXACT_GOALS: "EXACT_GOALS",
  BTTS: "BTTS",
  ODD_EVEN_GOALS: "ODD_EVEN_GOALS",
  HOME_TEAM_ODD_EVEN_GOALS: "HOME_TEAM_ODD_EVEN_GOALS",
  AWAY_TEAM_ODD_EVEN_GOALS: "AWAY_TEAM_ODD_EVEN_GOALS",
  SECOND_HALF_ODD_EVEN_GOALS: "SECOND_HALF_ODD_EVEN_GOALS",
  HALF_TIME_ODD_EVEN_GOALS: "HALF_TIME_ODD_EVEN_GOALS",
  WIN_TO_NIL: "WIN_TO_NIL",
  CLEAN_SHEET: "CLEAN_SHEET",
  HOME_TEAM_TO_SCORE: "HOME_TEAM_TO_SCORE",
  AWAY_TEAM_TO_SCORE: "AWAY_TEAM_TO_SCORE",
  TEAM_TOTAL_GOALS: "TEAM_TOTAL_GOALS",
  TEAM_GOAL_RANGE: "TEAM_GOAL_RANGE",
  GOAL_RANGE: "GOAL_RANGE",
  // audit-match (Arsenal vs Coventry City): cumulative multi-goal ladder,
  // distinct market family from GOAL_RANGE's disjoint exhaustive bands.
  MULTI_GOAL_RANGE: "MULTI_GOAL_RANGE",
    BOTH_HALVES_GOALS: "BOTH_HALVES_GOALS",
    OWN_GOAL: "OWN_GOAL",
     FREE_KICK_GOAL: "FREE_KICK_GOAL",
    HOME_TEAM_FREE_KICK_GOAL: "HOME_TEAM_FREE_KICK_GOAL",
    AWAY_TEAM_FREE_KICK_GOAL: "AWAY_TEAM_FREE_KICK_GOAL",
    HEADER_GOAL: "HEADER_GOAL",
    HEADER_GOAL_BOTH_HALVES: "HEADER_GOAL_BOTH_HALVES",
    TEAM_HEADER_GOAL: "TEAM_HEADER_GOAL",
     PENALTY_GOAL: "PENALTY_GOAL",
     BTTS_PENALTY: "BTTS_PENALTY",
     HALF_TIME_BTTS_PENALTY: "HALF_TIME_BTTS_PENALTY",
     SECOND_HALF_BTTS_PENALTY: "SECOND_HALF_BTTS_PENALTY",
     BTTS_HEAD_GOALS: "BTTS_HEAD_GOALS",
     BTTS_FREE_KICK: "BTTS_FREE_KICK",
     BTTS_2PLUS_GOALS: "BTTS_2PLUS_GOALS",
     WINNING_MARGIN: "WINNING_MARGIN",
  WIN_OR_WIN_BY_2: "WIN_OR_WIN_BY_2",
  HALF_TIME_GOAL_RANGE: "HALF_TIME_GOAL_RANGE",
  SECOND_HALF_GOAL_RANGE: "SECOND_HALF_GOAL_RANGE",
  // Handicap markets
  ASIAN_HANDICAP: "ASIAN_HANDICAP",
  ASIAN_HANDICAP_PUSH: "ASIAN_HANDICAP_PUSH",
  EUROPEAN_HANDICAP: "EUROPEAN_HANDICAP",
  ASIAN_HANDICAP_3WAY: "ASIAN_HANDICAP_3WAY",
  SECOND_HALF_EUROPEAN_HANDICAP: "SECOND_HALF_EUROPEAN_HANDICAP",
  // Half-time markets
  HALF_TIME_RESULT: "HALF_TIME_RESULT",
  HALF_TIME_DOUBLE_CHANCE: "HALF_TIME_DOUBLE_CHANCE",
  HALF_TIME_DRAW_NO_BET: "HALF_TIME_DRAW_NO_BET",
  HALF_TIME_TOTAL_GOALS: "HALF_TIME_TOTAL_GOALS",
  HALF_TIME_TOTAL_GOALS_ASIAN: "HALF_TIME_TOTAL_GOALS_ASIAN", // Integer lines with push/refund possibility (1st half)
  HALF_TIME_TEAM_TOTAL_GOALS: "HALF_TIME_TEAM_TOTAL_GOALS",
  HALF_TIME_EXACT_GOALS: "HALF_TIME_EXACT_GOALS",
  HALF_TIME_FIRST_GOAL: "HALF_TIME_FIRST_GOAL",
  HALF_TIME_BTTS: "HALF_TIME_BTTS",
  HALF_TIME_RESULT_AND_BTTS: "HALF_TIME_RESULT_AND_BTTS",
  HALF_TIME_RESULT_AND_TOTAL: "HALF_TIME_RESULT_AND_TOTAL",
  HALF_TIME_DOUBLE_CHANCE_BTTS: "HALF_TIME_DOUBLE_CHANCE_BTTS",
  FIRST_HALF_ASIAN_HANDICAP: "FIRST_HALF_ASIAN_HANDICAP",
  FIRST_HALF_ASIAN_HANDICAP_PUSH: "FIRST_HALF_ASIAN_HANDICAP_PUSH",
  FIRST_HALF_EUROPEAN_HANDICAP: "FIRST_HALF_EUROPEAN_HANDICAP",
    HALF_TIME_HOME_TO_SCORE: "HALF_TIME_HOME_TO_SCORE",
    HALF_TIME_AWAY_TO_SCORE: "HALF_TIME_AWAY_TO_SCORE",
    HALF_TIME_HOME_CLEAN_SHEET: "HALF_TIME_HOME_CLEAN_SHEET",
    HALF_TIME_AWAY_CLEAN_SHEET: "HALF_TIME_AWAY_CLEAN_SHEET",
    HALF_TIME_HEADER_GOAL: "HALF_TIME_HEADER_GOAL",
    HALF_TIME_PENALTY_GOAL: "HALF_TIME_PENALTY_GOAL",
    SECOND_HALF_PENALTY_GOAL: "SECOND_HALF_PENALTY_GOAL",

   SECOND_HALF_RESULT: "SECOND_HALF_RESULT",
  SECOND_HALF_DOUBLE_CHANCE: "SECOND_HALF_DOUBLE_CHANCE",
  SECOND_HALF_TOTAL_GOALS: "SECOND_HALF_TOTAL_GOALS",
  SECOND_HALF_TOTAL_GOALS_ASIAN: "SECOND_HALF_TOTAL_GOALS_ASIAN", // Integer lines with push/refund possibility (2nd half)
  SECOND_HALF_TEAM_TOTAL_GOALS: "SECOND_HALF_TEAM_TOTAL_GOALS",
  SECOND_HALF_EXACT_GOALS: "SECOND_HALF_EXACT_GOALS",
  SECOND_HALF_BTTS: "SECOND_HALF_BTTS",
  SECOND_HALF_RESULT_AND_TOTAL: "SECOND_HALF_RESULT_AND_TOTAL",
  SECOND_HALF_RESULT_AND_BTTS: "SECOND_HALF_RESULT_AND_BTTS",
  SECOND_HALF_DOUBLE_CHANCE_BTTS: "SECOND_HALF_DOUBLE_CHANCE_BTTS",
  SECOND_HALF_HOME_TO_SCORE: "SECOND_HALF_HOME_TO_SCORE",
   SECOND_HALF_AWAY_TO_SCORE: "SECOND_HALF_AWAY_TO_SCORE",
  SECOND_HALF_HOME_CLEAN_SHEET: "SECOND_HALF_HOME_CLEAN_SHEET",
  SECOND_HALF_AWAY_CLEAN_SHEET: "SECOND_HALF_AWAY_CLEAN_SHEET",
   SECOND_HALF_HEADER_GOAL: "SECOND_HALF_HEADER_GOAL",
   SECOND_HALF_ASIAN_HANDICAP: "SECOND_HALF_ASIAN_HANDICAP",
   SECOND_HALF_ASIAN_HANDICAP_PUSH: "SECOND_HALF_ASIAN_HANDICAP_PUSH",
  SECOND_HALF_FIRST_GOAL: "SECOND_HALF_FIRST_GOAL",
  AWAY_WIN_OR_UNDER: "AWAY_WIN_OR_UNDER",
  PLAYER_SHOTS_LINEUP: "PLAYER_SHOTS_LINEUP",
  PLAYER_SHOTS_ON_TARGET_LINEUP: "PLAYER_SHOTS_ON_TARGET_LINEUP",
  PLAYER_ASSISTS_LINEUP: "PLAYER_ASSISTS_LINEUP",
  PLAYER_GOALS_LINEUP: "PLAYER_GOALS_LINEUP",
  PLAYER_PASSES_LINEUP: "PLAYER_PASSES_LINEUP",
  PLAYER_TACKLES_LINEUP: "PLAYER_TACKLES_LINEUP",
  PLAYER_CARDS_LINEUP: "PLAYER_CARDS_LINEUP",
  HOME_GOALSCORER_FIRST: "HOME_GOALSCORER_FIRST",
  AWAY_GOALSCORER_FIRST: "AWAY_GOALSCORER_FIRST",
  HOME_GOALSCORER_LAST: "HOME_GOALSCORER_LAST",
  AWAY_GOALSCORER_LAST: "AWAY_GOALSCORER_LAST",
  SECOND_HALF_CORRECT_SCORE: "SECOND_HALF_CORRECT_SCORE",
  SECOND_HALF_DRAW_NO_BET: "SECOND_HALF_DRAW_NO_BET",
  
  TEAM_WIN_AT_LEAST_ONE_HALF: "TEAM_WIN_AT_LEAST_ONE_HALF",
  HOME_WIN_AT_LEAST_ONE_HALF: "HOME_WIN_AT_LEAST_ONE_HALF",
  AWAY_WIN_AT_LEAST_ONE_HALF: "AWAY_WIN_AT_LEAST_ONE_HALF",
  TEAM_WIN_BOTH_HALVES: "TEAM_WIN_BOTH_HALVES",
  HOME_WIN_BOTH_HALVES: "HOME_WIN_BOTH_HALVES",
  AWAY_WIN_BOTH_HALVES: "AWAY_WIN_BOTH_HALVES",
  HOME_WIN_TO_NIL: "HOME_WIN_TO_NIL",
  AWAY_WIN_TO_NIL: "AWAY_WIN_TO_NIL",
  HOME_EXACT_GOALS: "HOME_EXACT_GOALS",
  AWAY_EXACT_GOALS: "AWAY_EXACT_GOALS",
  HOME_GOAL_RANGE: "HOME_GOAL_RANGE",
  AWAY_GOAL_RANGE: "AWAY_GOAL_RANGE",
  HOME_CORNERS_RANGE: "HOME_CORNERS_RANGE",
  AWAY_CORNERS_RANGE: "AWAY_CORNERS_RANGE",
  HOME_CORNERS_RANGE_WIDE: "HOME_CORNERS_RANGE_WIDE",
  AWAY_CORNERS_RANGE_WIDE: "AWAY_CORNERS_RANGE_WIDE",
  HOME_HALF_WITH_MOST_GOALS: "HOME_HALF_WITH_MOST_GOALS",
  AWAY_HALF_WITH_MOST_GOALS: "AWAY_HALF_WITH_MOST_GOALS",
  HOME_SCORE_BOTH_HALVES: "HOME_SCORE_BOTH_HALVES",
  AWAY_SCORE_BOTH_HALVES: "AWAY_SCORE_BOTH_HALVES",
  SECOND_HALF_HOME_EXACT_GOALS: "SECOND_HALF_HOME_EXACT_GOALS",
  HOME_TEAM_TOTAL_GOALS: "HOME_TEAM_TOTAL_GOALS",
  AWAY_TEAM_TOTAL_GOALS: "AWAY_TEAM_TOTAL_GOALS",
  HALF_TIME_HOME_TEAM_TOTAL_GOALS: "HALF_TIME_HOME_TEAM_TOTAL_GOALS",
  HALF_TIME_AWAY_TEAM_TOTAL_GOALS: "HALF_TIME_AWAY_TEAM_TOTAL_GOALS",
  SECOND_HALF_HOME_TEAM_TOTAL_GOALS: "SECOND_HALF_HOME_TEAM_TOTAL_GOALS",
  SECOND_HALF_AWAY_TEAM_TOTAL_GOALS: "SECOND_HALF_AWAY_TEAM_TOTAL_GOALS",
  HALF_WITH_MORE_GOALS: "HALF_WITH_MORE_GOALS",
  TEAM_HALF_WITH_MORE_GOALS: "TEAM_HALF_WITH_MORE_GOALS",
  BTTS_BY_HALF: "BTTS_BY_HALF",
  TEAM_SCORES_BOTH_HALVES: "TEAM_SCORES_BOTH_HALVES",
  BOTH_HALVES_TOTAL_GOALS: "BOTH_HALVES_TOTAL_GOALS",
  BOTH_HALVES_UNDER_GOALS: "BOTH_HALVES_UNDER_GOALS",
  BOTH_HALVES_OVER_GOALS: "BOTH_HALVES_OVER_GOALS",
   // Score markets
   CORRECT_SCORE: "CORRECT_SCORE",
   CORRECT_SCORE_GROUP: "CORRECT_SCORE_GROUP",
   HALF_TIME_CORRECT_SCORE: "HALF_TIME_CORRECT_SCORE",
   HT_FT_CORRECT_SCORE: "HT_FT_CORRECT_SCORE",
  // Player markets (ZAWODNICY)
  GOALSCORER_FIRST: "GOALSCORER_FIRST",
  GOALSCORER_LAST: "GOALSCORER_LAST",
  GOALSCORER_ANYTIME: "GOALSCORER_ANYTIME",
  PLAYER_SHOTS: "PLAYER_SHOTS",
  PLAYER_CARDS: "PLAYER_CARDS",
  // audit-match (Arsenal vs Coventry City): betcris's yellow-only card
  // market is a distinct bet from PLAYER_CARDS (any card) — see catalog
  // entry comment for the odds evidence.
  PLAYER_YELLOW_CARD: "PLAYER_YELLOW_CARD",
   PLAYER_ASSISTS: "PLAYER_ASSISTS",
   PLAYER_ASSIST_PAIRS: "PLAYER_ASSIST_PAIRS",
   PLAYER_ASSIST_TRIPLE: "PLAYER_ASSIST_TRIPLE",
   PLAYER_GOALS: "PLAYER_GOALS",
   PLAYER_TACKLES: "PLAYER_TACKLES",
  PLAYER_INTERCEPTIONS: "PLAYER_INTERCEPTIONS",
  PLAYER_FOULS_WON: "PLAYER_FOULS_WON",
  PLAYER_FOULS: "PLAYER_FOULS",
  PLAYER_SAVES: "PLAYER_SAVES",
  PLAYER_RED_CARD: "PLAYER_RED_CARD",
  PLAYER_FREE_KICK_GOAL: "PLAYER_FREE_KICK_GOAL",
  PLAYER_HEADER_GOAL: "PLAYER_HEADER_GOAL",
  PLAYER_GOAL_AND_ASSIST: "PLAYER_GOAL_AND_ASSIST",
  PENALTY_SCORER: "PENALTY_SCORER",
  // Statistics markets (STATYSTYKI)
  CORNERS_TOTAL: "CORNERS_TOTAL",
  CORNERS_TEAM: "CORNERS_TEAM",
  EACH_TEAM_TOTAL_CORNERS_OVER: "EACH_TEAM_TOTAL_CORNERS_OVER",
  EACH_TEAM_TOTAL_CARDS_OVER: "EACH_TEAM_TOTAL_CARDS_OVER",
   CORNERS_RACE: "CORNERS_RACE",
    FOUL_RACE: "FOUL_RACE",
    CORNERS_RANGE: "CORNERS_RANGE",
   CORNERS_TEAM_RANGE: "CORNERS_TEAM_RANGE",
   FIRST_CORNER: "FIRST_CORNER",
   LAST_CORNER: "LAST_CORNER",
   HALF_TIME_LAST_CORNER: "HALF_TIME_LAST_CORNER",
  NEXT_CORNER_1H: "NEXT_CORNER_1H",
  CORNERS_HANDICAP: "CORNERS_HANDICAP",
  HALF_TIME_CORNERS_TOTAL: "HALF_TIME_CORNERS_TOTAL",
  HALF_TIME_CORNERS_TEAM: "HALF_TIME_CORNERS_TEAM",
  HALF_TIME_CORNERS_RACE: "HALF_TIME_CORNERS_RACE",
  HALF_TIME_CORNERS_HANDICAP: "HALF_TIME_CORNERS_HANDICAP",
  HALF_TIME_CORNERS_RANGE: "HALF_TIME_CORNERS_RANGE",
  HALF_TIME_CORNERS_TEAM_RANGE: "HALF_TIME_CORNERS_TEAM_RANGE",
  HALF_TIME_HOME_EXACT_CORNERS: "HALF_TIME_HOME_EXACT_CORNERS",
  HALF_TIME_AWAY_EXACT_CORNERS: "HALF_TIME_AWAY_EXACT_CORNERS",
  HALF_TIME_CORNERS_ODD_EVEN: "HALF_TIME_CORNERS_ODD_EVEN",
  CORNERS_ODD_EVEN: "CORNERS_ODD_EVEN",
  CARDS_TOTAL: "CARDS_TOTAL",
   HALF_TIME_CARDS_TOTAL: "HALF_TIME_CARDS_TOTAL",
   CARDS_EXACT_RANGE: "CARDS_EXACT_RANGE",
    CARDS_TEAM: "CARDS_TEAM",
    CARDS_RACE: "CARDS_RACE",
    HALF_TIME_CARDS_RACE: "HALF_TIME_CARDS_RACE",
    FIRST_CARD: "FIRST_CARD",
    FIRST_HALF_FIRST_CARD: "FIRST_HALF_FIRST_CARD",
    FOULS_TOTAL: "FOULS_TOTAL",
   OFFSIDES_TOTAL: "OFFSIDES_TOTAL",
   OFFSIDES_1X2: "OFFSIDES_1X2",
   HOME_TEAM_TOTAL_OFFSIDES: "HOME_TEAM_TOTAL_OFFSIDES",
   AWAY_TEAM_TOTAL_OFFSIDES: "AWAY_TEAM_TOTAL_OFFSIDES",
    HALF_TIME_RED_CARD: "HALF_TIME_RED_CARD",
    RED_CARD: "RED_CARD",
    RED_CARD_TEAM: "RED_CARD_TEAM",
   FIRST_HALF_CARDS_1X2: "FIRST_HALF_CARDS_1X2",
    PENALTY_AWARDED: "PENALTY_AWARDED",
   RED_CARD_AND_PENALTY: "RED_CARD_AND_PENALTY",
   MOST_SHOTS_ON_TARGET: "MOST_SHOTS_ON_TARGET",
    MOST_SHOTS: "MOST_SHOTS",
    TOTAL_SHOTS_ON_TARGET: "TOTAL_SHOTS_ON_TARGET",
    TEAM_TOTAL_SHOTS_ON_TARGET: "TEAM_TOTAL_SHOTS_ON_TARGET",
    TOTAL_SHOTS: "TOTAL_SHOTS",
    TEAM_TOTAL_SHOTS: "TEAM_TOTAL_SHOTS",
    TEAM_TOTAL_TACKLES: "TEAM_TOTAL_TACKLES",
    HOME_POSSESSION: "HOME_POSSESSION",
   AWAY_POSSESSION: "AWAY_POSSESSION",
  // Goals timing markets
  TEAMS_TO_SCORE: "TEAMS_TO_SCORE",
  FIRST_TEAM_TO_SCORE: "FIRST_TEAM_TO_SCORE",
  LAST_TEAM_TO_SCORE: "LAST_TEAM_TO_SCORE",
  FIRST_GOAL_TIME: "FIRST_GOAL_TIME",
  FIRST_GOAL_TIME_ALT: "FIRST_GOAL_TIME_ALT",
  TIME_PERIOD_RESULT: "TIME_PERIOD_RESULT",
  FIRST_GOAL_AND_RESULT: "FIRST_GOAL_AND_RESULT",
  // Additional player markets
  PLAYER_GOAL_AND_RESULT: "PLAYER_GOAL_AND_RESULT",
  PLAYER_SHOTS_ON_TARGET: "PLAYER_SHOTS_ON_TARGET",
  PLAYER_PASSES: "PLAYER_PASSES",
   PLAYER_2_OR_MORE_GOALS: "PLAYER_2_OR_MORE_GOALS",
   PLAYER_3_OR_MORE_GOALS: "PLAYER_3_OR_MORE_GOALS",
   // audit-match (Arsenal vs Coventry City), round 8 cat-add-player4: standalone
   // one-price 4+ product (betcris/lvbet), distinct from the PLAYER_GOALS ladder.
   PLAYER_4_OR_MORE_GOALS: "PLAYER_4_OR_MORE_GOALS",
    PLAYER_HAT_TRICK: "PLAYER_HAT_TRICK",
    TEAM_TOTAL_SCORERS: "TEAM_TOTAL_SCORERS",
    TWO_PLAYERS_COMBINED_GOALS: "TWO_PLAYERS_COMBINED_GOALS",
    THREE_PLAYERS_COMBINED_GOALS: "THREE_PLAYERS_COMBINED_GOALS",
    TWO_PLAYERS_ANYTIME: "TWO_PLAYERS_ANYTIME",
  BOTH_PLAYERS_ANYTIME: "BOTH_PLAYERS_ANYTIME",
  // audit-match (Arsenal vs Coventry City): betclic goal-or-assist combo
  // markets (distinct from plain-goal TWO/BOTH_PLAYERS_ANYTIME).
  TWO_PLAYERS_GOAL_OR_ASSIST: "TWO_PLAYERS_GOAL_OR_ASSIST",
  BOTH_PLAYERS_GOAL_OR_ASSIST: "BOTH_PLAYERS_GOAL_OR_ASSIST",
  // audit-match (Arsenal vs Coventry City): betclic "any of N players scores
  // 2+/3+ goals" combo markets (distinct from *_COMBINED_GOALS, which sums
  // goals jointly instead of requiring one player to reach the threshold).
  TWO_PLAYERS_ANY_2PLUS_GOALS: "TWO_PLAYERS_ANY_2PLUS_GOALS",
  THREE_PLAYERS_ANY_2PLUS_GOALS: "THREE_PLAYERS_ANY_2PLUS_GOALS",
  THREE_PLAYERS_ANY_3PLUS_GOALS: "THREE_PLAYERS_ANY_3PLUS_GOALS",
  HALF_TIME_TWO_PLAYERS_ANYTIME: "HALF_TIME_TWO_PLAYERS_ANYTIME",
  // audit-match (Arsenal vs Coventry City), catalog issue 2/12: betclic
  // "Obaj gracze strzelą w 1. połowa" (both named players score in 1st
  // half, AND semantics) — distinct from the OR-semantics
  // HALF_TIME_TWO_PLAYERS_ANYTIME above, mirrors BOTH_PLAYERS_ANYTIME's
  // relationship to TWO_PLAYERS_ANYTIME for the full match.
  HALF_TIME_BOTH_PLAYERS_ANYTIME: "HALF_TIME_BOTH_PLAYERS_ANYTIME",
  SECOND_HALF_TWO_PLAYERS_ANYTIME: "SECOND_HALF_TWO_PLAYERS_ANYTIME",
  HALF_TIME_THREE_PLAYERS_ANYTIME: "HALF_TIME_THREE_PLAYERS_ANYTIME",
  SECOND_HALF_THREE_PLAYERS_ANYTIME: "SECOND_HALF_THREE_PLAYERS_ANYTIME",
  ANY_PLAYER_FIRST_GOAL: "ANY_PLAYER_FIRST_GOAL",
  ANY_PLAYER_SCORES_BOTH_HALVES: "ANY_PLAYER_SCORES_BOTH_HALVES",
  SAME_PLAYER_SCORES_BOTH_HALVES: "SAME_PLAYER_SCORES_BOTH_HALVES",
  BOTH_PLAYERS_SCORE_BOTH_HALVES: "BOTH_PLAYERS_SCORE_BOTH_HALVES",
  ALL_PLAYERS_SCORE: "ALL_PLAYERS_SCORE",
  HAT_TRICK: "HAT_TRICK",
  SUBSTITUTE_GOAL: "SUBSTITUTE_GOAL",
  CARDS_EXACT: "CARDS_EXACT",
  HOME_EXACT_CARDS: "HOME_EXACT_CARDS",
  AWAY_EXACT_CARDS: "AWAY_EXACT_CARDS",
  HALF_TIME_HOME_EXACT_CARDS: "HALF_TIME_HOME_EXACT_CARDS",
  HALF_TIME_AWAY_EXACT_CARDS: "HALF_TIME_AWAY_EXACT_CARDS",
  CLEARANCES_TOTAL: "CLEARANCES_TOTAL",
  CLEARANCES_1X2: "CLEARANCES_1X2",
  FIRST_SHOT: "FIRST_SHOT",
  FIRST_SHOT_ON_TARGET: "FIRST_SHOT_ON_TARGET",
  CARDS_POINTS_OVER_UNDER: "CARDS_POINTS_OVER_UNDER",
  HALF_TIME_CARDS_POINTS_OVER_UNDER: "HALF_TIME_CARDS_POINTS_OVER_UNDER",
    THREE_PLAYERS_ANYTIME: "THREE_PLAYERS_ANYTIME",
  // Fortuna player props
  PLAYER_FIRST_OR_LAST_GOAL: "PLAYER_FIRST_OR_LAST_GOAL",
  PLAYER_FOOT_GOAL: "PLAYER_FOOT_GOAL",
  PLAYER_PENALTY_AREA_GOAL: "PLAYER_PENALTY_AREA_GOAL",
  PLAYER_GOAL_OUTSIDE_BOX: "PLAYER_GOAL_OUTSIDE_BOX",
  PLAYER_SHOTS_OUTSIDE_BOX: "PLAYER_SHOTS_OUTSIDE_BOX",
  PLAYER_SHOTS_IN_BOX: "PLAYER_SHOTS_IN_BOX",
  PLAYER_HEADER_SHOTS_ON_TARGET: "PLAYER_HEADER_SHOTS_ON_TARGET",
  PLAYER_OFFSIDES: "PLAYER_OFFSIDES",
  PLAYER_OFFSIDES_1H: "PLAYER_OFFSIDES_1H",
   // Combination markets (KOMBINACJE)
  RESULT_AND_BTTS: "RESULT_AND_BTTS",
  RESULT_AND_TOTAL: "RESULT_AND_TOTAL",
  RESULT_AND_FIRST_GOAL: "RESULT_AND_FIRST_GOAL",
  TOTAL_GOALS_AND_BTTS: "TOTAL_GOALS_AND_BTTS",
  BTTS_OR_OVER_2_5: "BTTS_OR_OVER_2_5",
  HALFTIME_FULLTIME: "HALFTIME_FULLTIME",
  HALFTIME_FULLTIME_AND_TOTAL: "HALFTIME_FULLTIME_AND_TOTAL",
  HT_OR_FT_RESULT: "HT_OR_FT_RESULT",
  MULTI_RESULT: "MULTI_RESULT",
  DOUBLE_RESULT: "DOUBLE_RESULT",
  DOUBLE_CHANCE_BTTS: "DOUBLE_CHANCE_BTTS",
  DOUBLE_CHANCE_TOTAL: "DOUBLE_CHANCE_TOTAL",
  // ===== Wave expansion: audited normalization expansion (144 new codes) =====
  EACH_TEAM_TOTAL_SHOTS_ON_TARGET_OVER: "EACH_TEAM_TOTAL_SHOTS_ON_TARGET_OVER",
  TEAM_TOTAL_FOULS: "TEAM_TOTAL_FOULS",
  BOTH_TEAMS_FOULS_OVER: "BOTH_TEAMS_FOULS_OVER",
  EACH_TEAM_OFFSIDES: "EACH_TEAM_OFFSIDES",
  PLAYER_GOAL_OR_ASSIST: "PLAYER_GOAL_OR_ASSIST",
  PLAYER_SHOTS_ON_TARGET_OUTSIDE_BOX: "PLAYER_SHOTS_ON_TARGET_OUTSIDE_BOX",
  HALF_TIME_LEAD_CHANGE: "HALF_TIME_LEAD_CHANGE",
  SUBSTITUTIONS_TOTAL: "SUBSTITUTIONS_TOTAL",
  HALF_TIME_WIN_TO_NIL: "HALF_TIME_WIN_TO_NIL",
  HALF_TIME_HOME_EXACT_GOALS: "HALF_TIME_HOME_EXACT_GOALS",
  SECOND_HALF_WIN_TO_NIL: "SECOND_HALF_WIN_TO_NIL",
  CARDS_HANDICAP: "CARDS_HANDICAP",
  RED_CARD_OR_PENALTY: "RED_CARD_OR_PENALTY",
  PENALTY_AWARDED_TEAM: "PENALTY_AWARDED_TEAM",
  HALF_TIME_DOUBLE_CHANCE_TOTAL: "HALF_TIME_DOUBLE_CHANCE_TOTAL",
  SECOND_HALF_DOUBLE_CHANCE_TOTAL: "SECOND_HALF_DOUBLE_CHANCE_TOTAL",
  INTERVAL_TOTAL_GOALS: "INTERVAL_TOTAL_GOALS",
  TIME_PERIOD_TOTAL_GOALS: "TIME_PERIOD_TOTAL_GOALS",
  FIRST_30_MIN_TOTAL_GOALS: "FIRST_30_MIN_TOTAL_GOALS",
  TIME_PERIOD_HANDICAP: "TIME_PERIOD_HANDICAP",
  TIME_PERIOD_ASIAN_HANDICAP: "TIME_PERIOD_ASIAN_HANDICAP",
  FIRST_GOAL_TIME_30MIN: "FIRST_GOAL_TIME_30MIN",
  HALF_TIME_WINNING_MARGIN: "HALF_TIME_WINNING_MARGIN",
  GOAL_OUTSIDE_BOX: "GOAL_OUTSIDE_BOX",
  BTTS_FIRST_60_MIN: "BTTS_FIRST_60_MIN",
  BTTS_FIRST_30_MIN: "BTTS_FIRST_30_MIN",
  FIRST_15_MIN_BTTS: "FIRST_15_MIN_BTTS",
  FIRST_15_MIN_HANDICAP: "FIRST_15_MIN_HANDICAP",
  SCORING_DRAW: "SCORING_DRAW",
  ANYTIME_CORRECT_SCORE: "ANYTIME_CORRECT_SCORE",
  AWAY_NO_BET: "AWAY_NO_BET",
  HOME_NO_BET: "HOME_NO_BET",
  DRAW_IN_AT_LEAST_ONE_HALF: "DRAW_IN_AT_LEAST_ONE_HALF",
  HALF_TIME_SECOND_HALF_RESULT: "HALF_TIME_SECOND_HALF_RESULT",
  SECOND_HALF_AWAY_WIN_TO_NIL: "SECOND_HALF_AWAY_WIN_TO_NIL",
  SECOND_HALF_HOME_WIN_TO_NIL: "SECOND_HALF_HOME_WIN_TO_NIL",
  SECOND_HALF_AWAY_WIN_EXACT_MARGIN: "SECOND_HALF_AWAY_WIN_EXACT_MARGIN",
  SECOND_HALF_HOME_WIN_EXACT_MARGIN: "SECOND_HALF_HOME_WIN_EXACT_MARGIN",
  // audit-match (Arsenal vs Coventry City), catalog issue 1/12: betcris
  // "<Team> wygra dokładną różnicą goli" (exact winning margin) for the
  // full match and 1st half, parallel to the SECOND_HALF_* pair above which
  // already existed. paramValue carries the margin (1/2/3/4), selections
  // are YES/NO on hitting that exact margin.
  HOME_WIN_EXACT_MARGIN: "HOME_WIN_EXACT_MARGIN",
  AWAY_WIN_EXACT_MARGIN: "AWAY_WIN_EXACT_MARGIN",
  FIRST_HALF_HOME_WIN_EXACT_MARGIN: "FIRST_HALF_HOME_WIN_EXACT_MARGIN",
  FIRST_HALF_AWAY_WIN_EXACT_MARGIN: "FIRST_HALF_AWAY_WIN_EXACT_MARGIN",
  HALF_TIME_AWAY_WIN_TO_NIL: "HALF_TIME_AWAY_WIN_TO_NIL",
  HALF_TIME_HOME_WIN_TO_NIL: "HALF_TIME_HOME_WIN_TO_NIL",
  FIRST_GOAL_METHOD: "FIRST_GOAL_METHOD",
  PENALTY_MISSED: "PENALTY_MISSED",
  AWAY_FIRST_GOAL_TIME: "AWAY_FIRST_GOAL_TIME",
  HOME_FIRST_GOAL_TIME: "HOME_FIRST_GOAL_TIME",
  AT_LEAST_ONE_TEAM_OVER_GOALS: "AT_LEAST_ONE_TEAM_OVER_GOALS",
  BOTH_TEAMS_PENALTY_AWARDED: "BOTH_TEAMS_PENALTY_AWARDED",
  TWO_PENALTIES_IN_MATCH: "TWO_PENALTIES_IN_MATCH",
  HALF_TIME_PENALTY_AWARDED: "HALF_TIME_PENALTY_AWARDED",
  PLAYER_GOAL_AND_TEAM_WIN: "PLAYER_GOAL_AND_TEAM_WIN",
  PLAYER_SCORES_BOTH_HALVES: "PLAYER_SCORES_BOTH_HALVES",
  HALF_TIME_GOALSCORER_ANYTIME: "HALF_TIME_GOALSCORER_ANYTIME",
  FIRST_PLAYER_CARDED: "FIRST_PLAYER_CARDED",
  FIRST_10_MIN_CORNERS_TOTAL: "FIRST_10_MIN_CORNERS_TOTAL",
  CORNERS_RACE_TO: "CORNERS_RACE_TO",
  CORNERS_TOTAL_3WAY: "CORNERS_TOTAL_3WAY",
  HALF_WITH_MOST_CORNERS: "HALF_WITH_MOST_CORNERS",
  FIRST_MINUTE_CORNER: "FIRST_MINUTE_CORNER",
  LAST_CARD: "LAST_CARD",
  FOULS_HANDICAP: "FOULS_HANDICAP",
  SECOND_HALF_CARDS_HANDICAP: "SECOND_HALF_CARDS_HANDICAP",
  SECOND_HALF_AWAY_TEAM_TOTAL_CARDS: "SECOND_HALF_AWAY_TEAM_TOTAL_CARDS",
  SECOND_HALF_HOME_TEAM_TOTAL_CARDS: "SECOND_HALF_HOME_TEAM_TOTAL_CARDS",
  SECOND_HALF_CARDS_TOTAL: "SECOND_HALF_CARDS_TOTAL",
  SECOND_HALF_CARDS_1X2: "SECOND_HALF_CARDS_1X2",
  HALF_TIME_CARDS_HANDICAP: "HALF_TIME_CARDS_HANDICAP",
  HALF_TIME_AWAY_TEAM_CARDS: "HALF_TIME_AWAY_TEAM_CARDS",
  HALF_TIME_HOME_TEAM_TOTAL_CARDS: "HALF_TIME_HOME_TEAM_TOTAL_CARDS",
  HALF_TIME_FOULS_HANDICAP: "HALF_TIME_FOULS_HANDICAP",
  TEAM_TOTAL_WOODWORK_SHOTS: "TEAM_TOTAL_WOODWORK_SHOTS",
  WOODWORK_SHOTS_HANDICAP: "WOODWORK_SHOTS_HANDICAP",
  WOODWORK_HITS_1X2: "WOODWORK_HITS_1X2",
  POST_OR_CROSSBAR_TOTAL: "POST_OR_CROSSBAR_TOTAL",
  GOAL_KICKS_HANDICAP: "GOAL_KICKS_HANDICAP",
  THROW_INS_HANDICAP: "THROW_INS_HANDICAP",
  THROW_INS_1X2: "THROW_INS_1X2",
  SHOTS_HANDICAP: "SHOTS_HANDICAP",
  FIRST_MINUTE_GOAL: "FIRST_MINUTE_GOAL",
  RED_CARDS_TOTAL: "RED_CARDS_TOTAL",
  HALF_TIME_FOULS_TOTAL: "HALF_TIME_FOULS_TOTAL",
  HALF_TIME_HOME_TEAM_FOULS_TOTAL: "HALF_TIME_HOME_TEAM_FOULS_TOTAL",
  HALF_TIME_AWAY_TEAM_TOTAL_FOULS: "HALF_TIME_AWAY_TEAM_TOTAL_FOULS",
  CARDS_POINTS_1X2: "CARDS_POINTS_1X2",
  CARDS_POINTS_HANDICAP: "CARDS_POINTS_HANDICAP",
  BOTH_TEAMS_CARDED: "BOTH_TEAMS_CARDED",
  STRAIGHT_RED_CARD: "STRAIGHT_RED_CARD",
  FIRST_OFFSIDE: "FIRST_OFFSIDE",
  PENALTY_OR_RED_CARD: "PENALTY_OR_RED_CARD",
  BOTH_HALVES_CARDS: "BOTH_HALVES_CARDS",
  THROW_INS_TOTAL: "THROW_INS_TOTAL",
  HOME_TEAM_TOTAL_THROW_INS: "HOME_TEAM_TOTAL_THROW_INS",
  AWAY_TEAM_TOTAL_THROW_INS: "AWAY_TEAM_TOTAL_THROW_INS",
  SHOTS_ON_TARGET_HANDICAP: "SHOTS_ON_TARGET_HANDICAP",
  BOTH_TEAMS_CARD_BOTH_HALVES: "BOTH_TEAMS_CARD_BOTH_HALVES",
  FIRST_10_MIN_CARDS: "FIRST_10_MIN_CARDS",
  BOTH_TEAMS_2PLUS_CARDS: "BOTH_TEAMS_2PLUS_CARDS",
  TOTAL_SHOTS_ON_TARGET_RANGE: "TOTAL_SHOTS_ON_TARGET_RANGE",
  HOME_TEAM_TOTAL_FOULS: "HOME_TEAM_TOTAL_FOULS",
  AWAY_TEAM_TOTAL_FOULS: "AWAY_TEAM_TOTAL_FOULS",
  GOAL_KICKS_TOTAL: "GOAL_KICKS_TOTAL",
  AWAY_TEAM_GOAL_KICKS: "AWAY_TEAM_GOAL_KICKS",
  HOME_TEAM_TOTAL_GOAL_KICKS: "HOME_TEAM_TOTAL_GOAL_KICKS",
  PLAYER_HIT_WOODWORK: "PLAYER_HIT_WOODWORK",
  TOTAL_SHOTS_ON_TARGET_OUTSIDE_BOX: "TOTAL_SHOTS_ON_TARGET_OUTSIDE_BOX",
  SECOND_HALF_ADDED_TIME_CARD: "SECOND_HALF_ADDED_TIME_CARD",
  PLAYER_SCORE_FIRST_10_MIN: "PLAYER_SCORE_FIRST_10_MIN",
  CARDS_ODD_EVEN: "CARDS_ODD_EVEN",
  SECOND_HALF_GOALSCORER_ANYTIME: "SECOND_HALF_GOALSCORER_ANYTIME",
  OFFSIDES_HANDICAP: "OFFSIDES_HANDICAP",
  BOTH_TEAMS_RED_CARD: "BOTH_TEAMS_RED_CARD",
  XG_HANDICAP: "XG_HANDICAP",
  PLAYER_RIGHT_FOOT_GOAL: "PLAYER_RIGHT_FOOT_GOAL",
  PLAYER_LEFT_FOOT_GOAL: "PLAYER_LEFT_FOOT_GOAL",
  ANY_TEAM_WIN: "ANY_TEAM_WIN",
  TEAM_WIN_MATCH: "TEAM_WIN_MATCH",
  WIN_OR_BTTS: "WIN_OR_BTTS",
  DRAW_OR_BTTS: "DRAW_OR_BTTS",
  WIN_OR_UNDER: "WIN_OR_UNDER",
  DRAW_OR_OVER_2_5: "DRAW_OR_OVER_2_5",
  DRAW_OR_CLEAN_SHEET: "DRAW_OR_CLEAN_SHEET",
  HALF_TIME_RED_CARD_TEAM: "HALF_TIME_RED_CARD_TEAM",
  TEAM_TO_LEAD: "TEAM_TO_LEAD",
  TEAM_SCORES_TWO_CONSECUTIVE_GOALS: "TEAM_SCORES_TWO_CONSECUTIVE_GOALS",
  TEAM_TWO_GOALS_IN_A_ROW: "TEAM_TWO_GOALS_IN_A_ROW",
  ANY_TEAM_TO_WIN: "ANY_TEAM_TO_WIN",
  HALF_TIME_SUBSTITUTION: "HALF_TIME_SUBSTITUTION",
  TOTAL_XG: "TOTAL_XG",
  SAVES_TOTAL: "SAVES_TOTAL",
  PLAYER_OF_THE_MATCH: "PLAYER_OF_THE_MATCH",
  ANY_PLAYER_2_OR_MORE_GOALS: "ANY_PLAYER_2_OR_MORE_GOALS",
  GOAL_IN_FIRST_15_MIN: "GOAL_IN_FIRST_15_MIN",
  GOAL_IN_FIRST_30MIN: "GOAL_IN_FIRST_30MIN",
  GOAL_IN_INTERVAL: "GOAL_IN_INTERVAL",
  GOAL_IN_TIME_PERIOD: "GOAL_IN_TIME_PERIOD",
  TEAM_GOALS_BEFORE_MINUTE: "TEAM_GOALS_BEFORE_MINUTE",
  TOTAL_GOALS_BY_60_MIN: "TOTAL_GOALS_BY_60_MIN",
  TEAM_TOTAL_GOALS_FIRST_60MIN: "TEAM_TOTAL_GOALS_FIRST_60MIN",
  TOTAL_GOALS_BY_60MIN: "TOTAL_GOALS_BY_60MIN",
  SECOND_HALF_CORNERS_RACE: "SECOND_HALF_CORNERS_RACE",
  SECOND_HALF_CORNERS_TOTAL: "SECOND_HALF_CORNERS_TOTAL",
  // audit-match (Arsenal vs Coventry City): superbet id 240085, missing
  // 2nd-half counterpart to HALF_TIME_CORNERS_HANDICAP.
  SECOND_HALF_CORNERS_HANDICAP: "SECOND_HALF_CORNERS_HANDICAP",
  SECOND_HALF_CORNERS_TEAM: "SECOND_HALF_CORNERS_TEAM",
  HALF_TIME_FIRST_CORNER: "HALF_TIME_FIRST_CORNER",
  HALF_TIME_CARDS_TEAM: "HALF_TIME_CARDS_TEAM",
  MISSED_PENALTY: "MISSED_PENALTY",
  PLAYER_GOAL_TEAM_LOSES: "PLAYER_GOAL_TEAM_LOSES",
  HALF_WITH_MORE_CORNERS: "HALF_WITH_MORE_CORNERS",
  DRAW_AT_LEAST_ONE_HALF: "DRAW_AT_LEAST_ONE_HALF",
  KICKOFF_TEAM: "KICKOFF_TEAM",
  FIRST_CARD_PLAYER: "FIRST_CARD_PLAYER",
  SCORE_DURING_MATCH: "SCORE_DURING_MATCH",
  HALF_TIME_GOAL: "HALF_TIME_GOAL",
  PLAYER_GOAL_FIRST_10_MIN: "PLAYER_GOAL_FIRST_10_MIN",
  DIFFERENT_HALF_WINNERS: "DIFFERENT_HALF_WINNERS",
  SECOND_HALF_RED_CARD: "SECOND_HALF_RED_CARD",
  LAST_YELLOW_CARD: "LAST_YELLOW_CARD",
  DIRECT_RED_CARD: "DIRECT_RED_CARD",
  BOTH_TEAMS_MIN_CARDS: "BOTH_TEAMS_MIN_CARDS",
  EXACT_GOALS_YN: "EXACT_GOALS_YN",
  HALF_TIME_LAST_TEAM_TO_SCORE: "HALF_TIME_LAST_TEAM_TO_SCORE",
  HALF_TIME_FOUL_RACE: "HALF_TIME_FOUL_RACE",
  SECOND_HALF_TEAM_GOAL_RANGE: "SECOND_HALF_TEAM_GOAL_RANGE",
  SECOND_HALF_GOAL: "SECOND_HALF_GOAL",
  TEAM_SCORE_BY_HALF: "TEAM_SCORE_BY_HALF",
  SECOND_HALF_LAST_TEAM_TO_SCORE: "SECOND_HALF_LAST_TEAM_TO_SCORE",
  SECOND_HALF_CARDS_TEAM: "SECOND_HALF_CARDS_TEAM",
  GOALKEEPER_SAVES_OVER: "GOALKEEPER_SAVES_OVER",
  AT_LEAST_ONE_TEAM_TOTAL_GOALS: "AT_LEAST_ONE_TEAM_TOTAL_GOALS",
  PLAYER_FOULS_OVER: "PLAYER_FOULS_OVER",
  TEAM_TOTAL_THROW_INS: "TEAM_TOTAL_THROW_INS",
  TIME_PERIOD_CORNERS_TOTAL: "TIME_PERIOD_CORNERS_TOTAL",
  HALF_TIME_TEAM_FOULS: "HALF_TIME_TEAM_FOULS",
  FIRST_PERIOD_THROW_INS: "FIRST_PERIOD_THROW_INS",
  PLAYER_SHOTS_OVER: "PLAYER_SHOTS_OVER",
  VAR_REVIEWS_TOTAL: "VAR_REVIEWS_TOTAL",
  MEDICAL_AIDS_TOTAL: "MEDICAL_AIDS_TOTAL",
  YELLOW_CARDS_TOTAL: "YELLOW_CARDS_TOTAL",
  THROW_INS_TEAM: "THROW_INS_TEAM",
  TEAM_THROW_INS: "TEAM_THROW_INS",
  TEAM_GOAL_KICKS: "TEAM_GOAL_KICKS",
  TEAM_TOTAL_GOAL_KICKS: "TEAM_TOTAL_GOAL_KICKS",
  COMEBACK: "COMEBACK",
  HALF_TIME_TOTAL_SHOTS_ON_TARGET: "HALF_TIME_TOTAL_SHOTS_ON_TARGET",
  BOTH_TEAMS_CORNERS_EACH_HALF: "BOTH_TEAMS_CORNERS_EACH_HALF",
  TEAM_CORNERS_BOTH_HALVES_OVER: "TEAM_CORNERS_BOTH_HALVES_OVER",
  BOTH_TEAMS_OVER_CORNERS: "BOTH_TEAMS_OVER_CORNERS",
  BOTH_TEAMS_CARDS_OVER: "BOTH_TEAMS_CARDS_OVER",
  EACH_TEAM_SHOTS_ON_TARGET: "EACH_TEAM_SHOTS_ON_TARGET",
  BOTH_TEAMS_OVER_FOULS: "BOTH_TEAMS_OVER_FOULS",
  EITHER_TEAM_TO_WIN: "EITHER_TEAM_TO_WIN",
  HOME_WIN_NO_BET: "HOME_WIN_NO_BET",
  DOUBLE_CHANCE_HALF_TIME_BTTS: "DOUBLE_CHANCE_HALF_TIME_BTTS",
  DOUBLE_CHANCE_SECOND_HALF_BTTS: "DOUBLE_CHANCE_SECOND_HALF_BTTS",
  FIRST_CARDED_PLAYER: "FIRST_CARDED_PLAYER",
  ASSIST_SCORER_ANYTIME: "ASSIST_SCORER_ANYTIME",
  PLAYER_SHOTS_ANYTIME: "PLAYER_SHOTS_ANYTIME",
  ONE_TEAM_TO_SCORE: "ONE_TEAM_TO_SCORE",
  NEXT_GOAL: "NEXT_GOAL",
  TOTAL_GOALS_3WAY: "TOTAL_GOALS_3WAY",
  DOUBLE_CHANCE_GOAL_RANGE: "DOUBLE_CHANCE_GOAL_RANGE",
  RESULT_OR_BTTS: "RESULT_OR_BTTS",
  HALFTIME_FULLTIME_DOUBLE_CHANCE: "HALFTIME_FULLTIME_DOUBLE_CHANCE",
  HALFTIME_FULLTIME_AND_BTTS: "HALFTIME_FULLTIME_AND_BTTS",
  SECOND_HALF_PENALTY_AWARDED: "SECOND_HALF_PENALTY_AWARDED",
  TEAM_MISSES_PENALTY: "TEAM_MISSES_PENALTY",
  BRACE_IN_MATCH: "BRACE_IN_MATCH",
  CORRECT_SCORE_COMBINATION: "CORRECT_SCORE_COMBINATION",
  BTTS_AT_LEAST_ONE_HALF: "BTTS_AT_LEAST_ONE_HALF",
  BTTS_BOTH_HALVES: "BTTS_BOTH_HALVES",
  EACH_TEAM_WINS_ONE_HALF: "EACH_TEAM_WINS_ONE_HALF",
  HALF_WITH_MORE_GOALS_DOUBLE_CHANCE: "HALF_WITH_MORE_GOALS_DOUBLE_CHANCE",
  SECOND_GOAL_TIME: "SECOND_GOAL_TIME",
  GOAL_IN_TIME_WINDOW: "GOAL_IN_TIME_WINDOW",
  GOAL_IN_90_PLUS: "GOAL_IN_90_PLUS",
  BOTH_TEAMS_TO_LEAD: "BOTH_TEAMS_TO_LEAD",
  ANY_TEAM_WINNING_MARGIN: "ANY_TEAM_WINNING_MARGIN",
  ANY_TEAM_EXACT_WINNING_MARGIN: "ANY_TEAM_EXACT_WINNING_MARGIN",
  ANY_TEAM_WINNING_MARGIN_2PLUS: "ANY_TEAM_WINNING_MARGIN_2PLUS",
  ANY_TEAM_WIN_BY_3PLUS: "ANY_TEAM_WIN_BY_3PLUS",
  HOME_WIN_BY_1_OR_DRAW: "HOME_WIN_BY_1_OR_DRAW",
  TEAM_FIRST_GOAL_PERIOD: "TEAM_FIRST_GOAL_PERIOD",
  RACE_TO_GOALS: "RACE_TO_GOALS",
  GOAL_RACE: "GOAL_RACE",
  TOTAL_GOAL_MINUTES: "TOTAL_GOAL_MINUTES",
  TEAM_GOAL_MINUTES_SUM: "TEAM_GOAL_MINUTES_SUM",
  DRAW_MINUTES_TOTAL: "DRAW_MINUTES_TOTAL",
  NEXT_TEAM_TO_SCORE: "NEXT_TEAM_TO_SCORE",
  SCORE_REACHED: "SCORE_REACHED",
  SCORE_OCCURS_DURING_MATCH: "SCORE_OCCURS_DURING_MATCH",
  SCORE_TO_OCCUR: "SCORE_TO_OCCUR",
  BOTH_TEAMS_UNDER_GOALS: "BOTH_TEAMS_UNDER_GOALS",
  SECOND_HALF_RESULT_OR_BTTS: "SECOND_HALF_RESULT_OR_BTTS",
  STOPPAGE_TIME_GOAL: "STOPPAGE_TIME_GOAL",
  ANY_TEAM_WINNING_MARGIN_EXACT: "ANY_TEAM_WINNING_MARGIN_EXACT",
  WINNING_MARGIN_ANY_EXACT: "WINNING_MARGIN_ANY_EXACT",
  ANY_TEAM_WIN_BY_MARGIN: "ANY_TEAM_WIN_BY_MARGIN",
  ANY_TEAM_WIN_BY_2PLUS: "ANY_TEAM_WIN_BY_2PLUS",
  WIN_BY_1_OR_DRAW: "WIN_BY_1_OR_DRAW",
  FIRST_GOAL_HALF: "FIRST_GOAL_HALF",
  TEAM_MINUTES_LEADING: "TEAM_MINUTES_LEADING",
  HALF_TIME_AND_SECOND_HALF_RESULT: "HALF_TIME_AND_SECOND_HALF_RESULT",
  BOTH_HALVES_OVER_COMBO: "BOTH_HALVES_OVER_COMBO",
  TIME_BAND_TOTAL_GOALS: "TIME_BAND_TOTAL_GOALS",
  TIME_SEGMENT_TOTAL_GOALS: "TIME_SEGMENT_TOTAL_GOALS",
  TIME_PERIOD_GOALS: "TIME_PERIOD_GOALS",
  // ===== Wave-B expansion: placeholder/superbet-pzbuk catalog codes =====
  GOAL_BY_MINUTE: "GOAL_BY_MINUTE",
  RESULT_AT_MINUTE: "RESULT_AT_MINUTE",
  TOTAL_GOALS_OVER_PICK: "TOTAL_GOALS_OVER_PICK",
  RESULT_OR_TOTAL: "RESULT_OR_TOTAL",
  NTH_CORNER: "NTH_CORNER",
  TOTAL_GOALS_OVER_LINES: "TOTAL_GOALS_OVER_LINES",
  TOTAL_GOALS_OVER_LINE: "TOTAL_GOALS_OVER_LINE",
  DOUBLE_RESULT_PAIR: "DOUBLE_RESULT_PAIR",
  SAME_RESULT_BOTH_HALVES: "SAME_RESULT_BOTH_HALVES",
  RESULT_AND_GOAL_RANGE: "RESULT_AND_GOAL_RANGE",
  HT_SCORE_AND_FT_RESULT: "HT_SCORE_AND_FT_RESULT",
  // ===== Fortuna final wave: new catalog codes =====
  WIN_AND_PLAYER_SHOTS_ON_TARGET: "WIN_AND_PLAYER_SHOTS_ON_TARGET",
  TOTAL_GOALS_MINIMUM: "TOTAL_GOALS_MINIMUM",
  TEAM_WIN_OR_OVER_GOALS: "TEAM_WIN_OR_OVER_GOALS",
  TEAM_WIN_OR_TOTAL_UNDER: "TEAM_WIN_OR_TOTAL_UNDER",
  VAR_REVIEW: "VAR_REVIEW",
  PENALTY_IN_BOTH_HALVES: "PENALTY_IN_BOTH_HALVES",
  TEAM_CLEAN_SHEET: "TEAM_CLEAN_SHEET",
  TEAM_WIN: "TEAM_WIN",
  HOME_CLEAN_SHEET: "HOME_CLEAN_SHEET",
  TEAM_WINS_MATCH: "TEAM_WINS_MATCH",
  HALF_TIME_STOPPAGE_TIME_GOAL: "HALF_TIME_STOPPAGE_TIME_GOAL",
  SECOND_HALF_ADDED_TIME_GOAL: "SECOND_HALF_ADDED_TIME_GOAL",
  INJURY_TIME_GOAL: "INJURY_TIME_GOAL",
  MATCH_HAS_WINNER: "MATCH_HAS_WINNER",
  // Match-audit wave (2026-06-27)
  TEAM_TO_QUALIFY: "TEAM_TO_QUALIFY",
  WIN_METHOD: "WIN_METHOD",
  EXTRA_TIME: "EXTRA_TIME",
  PENALTY_SHOOTOUT: "PENALTY_SHOOTOUT",
  DRAW_OR_UNDER_2_5: "DRAW_OR_UNDER_2_5",
  TEAM_WIN_OR_CLEAN_SHEET: "TEAM_WIN_OR_CLEAN_SHEET",
  HALF_TIME_TEAM_GOAL_RANGE: "HALF_TIME_TEAM_GOAL_RANGE",
  TEAM_FIRST_GOALSCORER: "TEAM_FIRST_GOALSCORER",
  HALF_TIME_OFFSIDES_HANDICAP: "HALF_TIME_OFFSIDES_HANDICAP",
  RESULT_OR_CORRECT_SCORE: "RESULT_OR_CORRECT_SCORE",
  TWO_PLAYERS_CARDED: "TWO_PLAYERS_CARDED",
  BTTS_AND_PLAYER_GOAL: "BTTS_AND_PLAYER_GOAL",
  FIRST_GOAL_KICK: "FIRST_GOAL_KICK",
  OWN_GOALS_TOTAL: "OWN_GOALS_TOTAL",
  HALF_TIME_SHOTS_HANDICAP: "HALF_TIME_SHOTS_HANDICAP",
  TEAM_WIN_AND_GOAL_RANGE: "TEAM_WIN_AND_GOAL_RANGE",
  BOTH_TEAMS_OVER_GOALS: "BOTH_TEAMS_OVER_GOALS",
  PLAYER_CARD_DOUBLE_CHANCE: "PLAYER_CARD_DOUBLE_CHANCE",
  HALF_TIME_OFFSIDES_1X2: "HALF_TIME_OFFSIDES_1X2",
  MATCH_RESOLUTION_METHOD: "MATCH_RESOLUTION_METHOD",
  TEAM_FIRST_GOAL_AND_TOTAL_GOALS: "TEAM_FIRST_GOAL_AND_TOTAL_GOALS",
  BTTS_OR_TOTAL_OVER: "BTTS_OR_TOTAL_OVER",
  AWAY_WIN_BY_1_OR_DRAW: "AWAY_WIN_BY_1_OR_DRAW",
  HALF_TIME_AWAY_EXACT_GOALS: "HALF_TIME_AWAY_EXACT_GOALS",
  SECOND_HALF_AWAY_EXACT_GOALS: "SECOND_HALF_AWAY_EXACT_GOALS",
  FIRST_10_MIN_TOTAL_GOALS: "FIRST_10_MIN_TOTAL_GOALS",
  TEAM_TOTAL_GOALS_FIRST_15MIN: "TEAM_TOTAL_GOALS_FIRST_15MIN",
  TEAM_TOTAL_GOALS_FIRST_30MIN: "TEAM_TOTAL_GOALS_FIRST_30MIN",
  TEAM_TOTAL_GOALS_FIRST_75MIN: "TEAM_TOTAL_GOALS_FIRST_75MIN",
  RESULT_AND_TEAM_GOALS: "RESULT_AND_TEAM_GOALS",
  TEAM_GOAL_RANGE_EXTRA: "TEAM_GOAL_RANGE_EXTRA",
  PLAYER_GOAL_OR_ASSIST_DOUBLE_CHANCE: "PLAYER_GOAL_OR_ASSIST_DOUBLE_CHANCE",
  EXACT_GOALS_COUNT_YN: "EXACT_GOALS_COUNT_YN",
  TEAM_BOTH_HALVES_OVER_GOALS: "TEAM_BOTH_HALVES_OVER_GOALS",
  EITHER_HALF_OVER_GOALS: "EITHER_HALF_OVER_GOALS",
  TOTAL_GOALS_BY_40_MIN: "TOTAL_GOALS_BY_40_MIN",
  RESULT_OR_TWO_GOAL_LEAD: "RESULT_OR_TWO_GOAL_LEAD",
  FIRST_30_MIN_HANDICAP: "FIRST_30_MIN_HANDICAP",
  FIRST_60_MIN_HANDICAP: "FIRST_60_MIN_HANDICAP",
  FIRST_75_MIN_HANDICAP: "FIRST_75_MIN_HANDICAP",
  TEAM_EXACT_GOALS_BANDS: "TEAM_EXACT_GOALS_BANDS",
  AWAY_CLEAN_SHEET: "AWAY_CLEAN_SHEET",
  MATCH_RESULT_OR_WIN_BY_2: "MATCH_RESULT_OR_WIN_BY_2",
  QUARTER_RESULT: "QUARTER_RESULT",
  AWAY_WIN_MATCH: "AWAY_WIN_MATCH",
  HOME_WIN_OR_OVER: "HOME_WIN_OR_OVER",
  AWAY_WIN_OR_OVER: "AWAY_WIN_OR_OVER",
  HOME_WIN_OR_UNDER: "HOME_WIN_OR_UNDER",
  EXTRA_TIME_GOAL: "EXTRA_TIME_GOAL",
  YELLOW_CARDS_1X2: "YELLOW_CARDS_1X2",
  HALF_TIME_SHOTS_ON_TARGET_HANDICAP: "HALF_TIME_SHOTS_ON_TARGET_HANDICAP",
  FIRST_10_MIN_CORNERS_TEAM: "FIRST_10_MIN_CORNERS_TEAM",
  RESULT_AND_TEAM_TOTAL_GOALS: "RESULT_AND_TEAM_TOTAL_GOALS",
  HALF_TIME_WIN_BY_EXACT_GOALS: "HALF_TIME_WIN_BY_EXACT_GOALS",
  CORNERS_TOTAL_RANGE: "CORNERS_TOTAL_RANGE",
  CARDS_TOTAL_RANGE: "CARDS_TOTAL_RANGE",
  HALF_TIME_CARDS_EXACT: "HALF_TIME_CARDS_EXACT",
  HALVES_GOALS_HANDICAP: "HALVES_GOALS_HANDICAP",
  RESULT_AND_EXACT_GOALS: "RESULT_AND_EXACT_GOALS",
  ASIAN_TOTAL_GOALS: "ASIAN_TOTAL_GOALS",
  CARDS_POINTS_RANGE: "CARDS_POINTS_RANGE",
  YELLOW_CARDS_RACE: "YELLOW_CARDS_RACE",
  SECOND_HALF_GOAL_BANDS: "SECOND_HALF_GOAL_BANDS",
  PLAYER_GOALS_1H: "PLAYER_GOALS_1H",
  PLAYER_FOULS_1H: "PLAYER_FOULS_1H",
  PLAYER_SHOTS_1H: "PLAYER_SHOTS_1H",
  PLAYER_SHOTS_ON_TARGET_1H: "PLAYER_SHOTS_ON_TARGET_1H",
  PLAYER_CARDS_1H: "PLAYER_CARDS_1H",
  PLAYER_FOOT_SHOTS_ON_TARGET: "PLAYER_FOOT_SHOTS_ON_TARGET",
  PLAYER_SHOTS_ON_TARGET_IN_BOX: "PLAYER_SHOTS_ON_TARGET_IN_BOX",
  PLAYER_GOAL_OR_CARD: "PLAYER_GOAL_OR_CARD",
  ASSISTS_TOTAL: "ASSISTS_TOTAL",
  HALF_TIME_DOUBLE_CHANCE_TOTAL_BTTS: "HALF_TIME_DOUBLE_CHANCE_TOTAL_BTTS",
  RESULT_OR_HALF_TIME_TOTAL: "RESULT_OR_HALF_TIME_TOTAL",
  HALF_TIME_HOME_EXACT_CARDS_POINTS: "HALF_TIME_HOME_EXACT_CARDS_POINTS",
  HALF_TIME_TOTAL_GOALS_3WAY: "HALF_TIME_TOTAL_GOALS_3WAY",
  CORNERS_RANGE_FINE: "CORNERS_RANGE_FINE",
  // Fallback
  OTHER: "OTHER",
} as const;
export type NormalizedMarketType = (typeof NormalizedMarketType)[keyof typeof NormalizedMarketType];

// ============================================================================
// NORMALIZED SELECTION
// ============================================================================

/**
 * Normalized selection types (canonical codes for all selections)
 */
export const NormalizedSelection = {
    HOME: "HOME",
    DRAW: "DRAW",
    AWAY: "AWAY",
    NONE: "NONE",
    TEAM_HOME: "TEAM_HOME",
    TEAM_AWAY: "TEAM_AWAY",
    ANY: "ANY",
    HOME_OR_DRAW: "HOME_OR_DRAW",
    DRAW_OR_AWAY: "DRAW_OR_AWAY",
    HOME_OR_AWAY: "HOME_OR_AWAY",
    OVER: "OVER",
    UNDER: "UNDER",
    YES: "YES",
    NO: "NO",
    ODD: "ODD",
    EVEN: "EVEN",
    UNKNOWN: "UNKNOWN",
    HOME_OVER: "HOME_OVER",
    HOME_UNDER: "HOME_UNDER",
    DRAW_OVER: "DRAW_OVER",
    DRAW_UNDER: "DRAW_UNDER",
    AWAY_OVER: "AWAY_OVER",
    AWAY_UNDER: "AWAY_UNDER",
    HOME_YES: "HOME_YES",
    HOME_NO: "HOME_NO",
    DRAW_YES: "DRAW_YES",
    DRAW_NO: "DRAW_NO",
    AWAY_YES: "AWAY_YES",
    AWAY_NO: "AWAY_NO",
    OVER_YES: "OVER_YES",
  OVER_NO: "OVER_NO",
  UNDER_YES: "UNDER_YES",
  UNDER_NO: "UNDER_NO",
  YES_YES: "YES_YES",
     YES_NO: "YES_NO",
     NO_YES: "NO_YES",
     NO_NO: "NO_NO",
     HOME_HOME: "HOME_HOME",
     HOME_AWAY: "HOME_AWAY",
     DRAW_HOME: "DRAW_HOME",
     DRAW_AWAY: "DRAW_AWAY",
     DRAW_NONE: "DRAW_NONE",
     AWAY_HOME: "AWAY_HOME",
     AWAY_AWAY: "AWAY_AWAY",
    "1X_YES": "1X_YES",
    "1X_NO": "1X_NO",
    "X2_YES": "X2_YES",
    "X2_NO": "X2_NO",
    "12_YES": "12_YES",
    "12_NO": "12_NO",
    PLAYER_PAIR: "PLAYER_PAIR",
    PLAYER_TRIO: "PLAYER_TRIO",
    HOME_WIN_GROUP_0: "HOME_WIN_GROUP_0",
    HOME_WIN_GROUP_1: "HOME_WIN_GROUP_1",
    HOME_WIN_GROUP_2: "HOME_WIN_GROUP_2",
    HOME_WIN_GROUP_3: "HOME_WIN_GROUP_3",
    AWAY_WIN_GROUP_1: "AWAY_WIN_GROUP_1",
    AWAY_WIN_GROUP_2: "AWAY_WIN_GROUP_2",
    AWAY_WIN_GROUP_3: "AWAY_WIN_GROUP_3",
    AWAY_WIN_GROUP_4: "AWAY_WIN_GROUP_4",
    HOME_OTHER: "HOME_OTHER",
    AWAY_OTHER: "AWAY_OTHER",
    "0-15": "0-15",
    "1-15": "1-15",
    "16-30": "16-30",
    "31-45": "31-45",
    "46-60": "46-60",
    "61-75": "61-75",
    "76-90": "76-90",
    "1-10": "1-10",
    "11-20": "11-20",
    "21-30": "21-30",
    "31-40": "31-40",
    "41-50": "41-50",
    "51-60": "51-60",
    "61-70": "61-70",
    "71-80": "71-80",
    "81-90": "81-90",
    TWO_TEAMS: "TWO_TEAMS",
    ONE_TEAM: "ONE_TEAM",
    ONE_TEAM_HOME: "ONE_TEAM_HOME",
    ONE_TEAM_AWAY: "ONE_TEAM_AWAY",
    ZERO_TEAMS: "ZERO_TEAMS",
    HOME_1ST: "HOME_1ST",
    HOME_2ND: "HOME_2ND",
    HOME_EQUAL: "HOME_EQUAL",
    AWAY_1ST: "AWAY_1ST",
    AWAY_2ND: "AWAY_2ND",
    AWAY_EQUAL: "AWAY_EQUAL",
  } as const;
  export type NormalizedSelection = (typeof NormalizedSelection)[keyof typeof NormalizedSelection];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function buildMarketKey(type: NormalizedMarketType, param?: string): string {
  if (!param) return type;
  const normalizedParam = param.replace(",", ".");
  return `${type}:${normalizedParam}`;
}

// ============================================================================
// ADDITIONAL TYPES (for normalization core)
// ============================================================================

export interface RawBookmakerMarket {
  bookmakerMarketId?: string | number;
  name: string;
  groupName?: string;
  /** Pre-extracted parameter value set by parser (e.g., after splitting multi-line markets by line) */
  paramValue?: string;
  selections: Array<{ name: string; odds: number; externalId?: string }>;
}

/**
 * Normalization context passed to normalizers
 */
export interface NormalizationContext {
  homeTeam: string;
  awayTeam: string;
  sportType?: string;
  leagueName?: string;
  /**
   * League slug (e.g. "world-cup-2026"). Used to resolve selection names that
   * differ in language from the canonical context team names (e.g. Polish
   * national-team names → canonical English) via the team-matcher alias maps.
   */
  league?: string;
}

/**
 * Output of a bookmaker normalizer
 */
export interface NormalizedMarketOutput {
  /** Canonical market code (e.g., "TOTAL_GOALS", "MATCH_WINNER") */
  marketCode: NormalizedMarketType;
  /** Parameter value if applicable (e.g., "2.5" for over/under) */
  paramValue?: string;
  /** Multiple parameter values for markets with multiple lines (e.g., ASIAN_HANDICAP_3WAY) */
  parameters?: string[];
  /** Unique market key: marketCode or marketCode:paramValue */
  marketKey: string;
  /** Custom label to override default market catalog label (e.g., "Czerwona kartka - Arsenal") */
  customLabel?: string;
  /** Normalized selections */
  selections: Array<{
    /** Canonical selection code (e.g., "HOME", "OVER", "YES") */
    code: NormalizedSelection;
    /** Original label for display/debug */
    label: string;
    /** Decimal odds */
    odds: number;
  }>;
  /** Debug info for troubleshooting */
  debug?: {
    rawName: string;
    rawId?: string | number;
    matchedBy?: "id" | "name" | "pattern";
  };
}

/**
 * Interface for bookmaker-specific market normalizers.
 * Each bookmaker implements this interface to handle its own market normalization.
 * 
 * This replaces the centralized pattern-matching approach with adapter-first normalization.
 */
export interface BookmakerMarketNormalizer {
  /** Bookmaker identifier (e.g., "sts", "fortuna") */
  bookmaker: string;
  
  /**
   * Normalize a single raw market to canonical format.
   * 
   * @param raw - Raw market data from the scraper
   * @param ctx - Context with team names and other metadata
   * @returns Normalized market or null if market should be skipped/unknown
   */
  normalizeMarket(
    raw: RawBookmakerMarket,
    ctx: NormalizationContext
  ): NormalizedMarketOutput | null;
  
  /**
   * Normalize multiple markets at once (batch processing).
   * Default implementation calls normalizeMarket for each.
   */
  normalizeMarkets?(
    markets: RawBookmakerMarket[],
    ctx: NormalizationContext
  ): NormalizedMarketOutput[];
}

export interface BookmakerMarketData {
  idMappings?: number[];
  additionalPatterns?: RegExp[];
  displayName?: string;
}

export interface MarketDefinition {
  code: string;
  slug?: string;
  numericId?: number;
  name_pl?: string;
  name_en?: string;
  labels?: { pl: string; en: string };
  category: MarketCategory;
  subCategory?: string;
  view_type?: ViewType;
  viewType?: ViewType;
  patterns?: (string | RegExp)[];
  selections?: string[];
  hasParameter?: boolean;
  parameterType?: ParameterType;
  extractParam?: (match: RegExpMatchArray) => string | undefined;
  bookmakerData?: Record<string, BookmakerMarketData>;
}

export interface NormalizedMarketSelection {
  name: string;
  normalizedName: NormalizedSelection;
  odds: number;
}

export interface NormalizedMarket {
  name: string;
  normalizedType: NormalizedMarketType;
  marketKey: string;
  category: MarketCategory;
  paramValue?: string;
  customLabel?: string;
  selections: NormalizedMarketSelection[];
}

export interface NormalizedSelectionResult {
  name: string;
  normalizedName: NormalizedSelection;
  odds: number;
}

export type ScrapedMarket = import("../../types/full-offer.js").ScrapedMarket;
